#define z_errmsg                    z_z_errmsg

#define unzClose                    z_unzClose
#define unzCloseCurrentFile         z_unzCloseCurrentFile
#define unzGetCurrentFileInfo       z_unzGetCurrentFileInfo
#define unzGetCurrentFileInfo64     z_unzGetCurrentFileInfo64
#define unzGetCurrentFileZStreamPos64   z_unzGetCurrentFileZStreamPos64
#define unzGetFilePos               z_unzGetFilePos
#define unzGetFilePos64             z_unzGetFilePos64
#define unzGetGlobalComment         z_unzGetGlobalComment
#define unzGetGlobalInfo            z_unzGetGlobalInfo
#define unzGetGlobalInfo64          z_unzGetGlobalInfo64
#define unzGetLocalExtrafield       z_unzGetLocalExtrafield
#define unzGetOffset                z_unzGetOffset
#define unzGetOffset64              z_unzGetOffset64
#define unzGoToFilePos              z_unzGoToFilePos
#define unzGoToFilePos64            z_unzGoToFilePos64
#define unzGoToFirstFile            z_unzGoToFirstFile
#define unzGoToNextFile             z_unzGoToNextFile
#define unzLocateFile               z_unzLocateFile
#define unzOpen                     z_unzOpen
#define unzOpen64                   z_unzOpen64
#define unzOpen2                    z_unzOpen2
#define unzOpen2_64                 z_unzOpen2_64
#define unzOpenCurrentFile          z_unzOpenCurrentFile
#define unzOpenCurrentFile2         z_unzOpenCurrentFile2
#define unzOpenCurrentFile3         z_unzOpenCurrentFile3
#define unzOpenCurrentFilePassword  z_unzOpenCurrentFilePassword
#define unzReadCurrentFile          z_unzReadCurrentFile
#define unzRepair				    z_unzRepair
#define unzSetOffset                z_unzSetOffset
#define unzSetOffset64              z_unzSetOffset64
#define unzStringFileNameCompare    z_unzStringFileNameCompare
#define unztell				        z_unztell
#define unztell64				    z_unztell64
#define unzeof				        z_unzeof
#define zipClose                    z_zipClose
#define zipClose2                   z_zipClose2
#define zipCloseFileInZip           z_zipCloseFileInZip
#define zipCloseFileInZipRaw        z_zipCloseFileInZipRaw
#define zipCloseFileInZipRaw64      z_zipCloseFileInZipRaw64
#define zipOpen                     z_zipOpen
#define zipOpen64                   z_zipOpen64
#define zipOpen2                    z_zipOpen2
#define zipOpen2_64                 z_zipOpen2_64
#define zipOpen3                    z_zipOpen3
#define zipOpenNewFileInZip         z_zipOpenNewFileInZip
#define zipOpenNewFileInZip64       z_zipOpenNewFileInZip64
#define zipOpenNewFileInZip2        z_zipOpenNewFileInZip2
#define zipOpenNewFileInZip2_64     z_zipOpenNewFileInZip2_64
#define zipOpenNewFileInZip3        z_zipOpenNewFileInZip3
#define zipOpenNewFileInZip3_64     z_zipOpenNewFileInZip3_64
#define zipOpenNewFileInZip4        z_zipOpenNewFileInZip4
#define zipOpenNewFileInZip4_64     z_zipOpenNewFileInZip4_64
#define zipRemoveExtraInfoBlock     z_zipRemoveExtraInfoBlock
#define zipWriteInFileInZip         z_zipWriteInFileInZip
#define gzopen						z_gzopen
#define gzopen64					z_gzopen64
#define gzdopen						z_gzdopen
#define gzbuffer					z_gzbuffer
#define gzseek						z_gzseek
#define gzseek64					z_gzseek64
#define gzsetparams					z_gzsetparams
#define gzread						z_gzread
#define gzwrite						z_gzwrite
#define gzprintf					z_gzprintf
#define gzputc						z_gzputc
#define gzputs						z_gzputs
#define gzgetc						z_gzgetc
#define gzgets						z_gzgets
#define gzungetc					z_gzungetc
#define gzrewind					z_gzrewind
#define gzeof						z_gzeof
#define gzclearerr					z_gzclearerr
#define gzflush						z_gzflush
#define gzdirect					z_gzdirect
#define gzerror						z_gzerror
#define gzclose						z_gzclose
#define gzclose_r					z_gzclose_r
#define gzclose_w					z_gzclose_w
#define gztell						z_gztell
#define gztell64					z_gztell64
#define gzoffset					z_gzoffset
#define gzoffset64					z_gzoffset64
#define gcrc32_combine				z_crc32_combine
#define gcrc32_combine64			z_crc32_combine64
