#define Z_PREFIX_SET
#define _dist_code                  lvzip__dist_code
#define _length_code                lvzip__length_code
#define _tr_align                   lvzip__tr_align
#define _tr_flush_block             lvzip__tr_flush_block
#define _tr_init                    lvzip__tr_init
#define _tr_stored_block            lvzip__tr_stored_block
#define _tr_tally                   lvzip__tr_tally
#define adler32                     lvzip_adler32
#define adler32_combine             lvzip_adler32_combine
#define adler32_combine64           lvzip_adler32_combine64
#define compress                    lvzip_compress
#define compress2                   lvzip_compress2
#define compressBound               lvzip_compressBound
#define crc32                       lvzip_crc32
#define crc32_combine               lvzip_crc32_combine
#define crc32_combine64             lvzip_crc32_combine64
#define deflate                     lvzip_deflate
#define deflate_copyright           lvzip_deflate_copyright
#define deflateBound                lvzip_deflateBound
#define deflateCopy                 lvzip_deflateCopy
#define deflateEnd                  lvzip_deflateEnd
#define deflateInit                 lvzip_deflateInit
#define deflateInit2                lvzip_deflateInit2
#define deflateParams               lvzip_deflateParams
#define deflatePrime                lvzip_deflatePrime
#define deflateReset                lvzip_deflateReset
#define deflateSetDictionary        lvzip_deflateSetDictionary
#define deflateSetHeader            lvzip_deflateSetHeader
#define deflateTune                 lvzip_deflateTune
#define get_crc_table               lvzip_get_crc_table
#define inflate                     lvzip_inflate
#define inflate_copyright           lvzip_inflate_copyright
#define inflate_table               lvzip_inflate_table
#define inflateBack                 lvzip_inflateBack
#define inflateBackEnd              lvzip_inflateBackEnd
#define inflateBackInit             lvzip_inflateBackInit
#define inflateCopy                 lvzip_inflateCopy
#define inflateEnd                  lvzip_inflateEnd
#define inflateGetHeader            lvzip_inflateGetHeader
#define inflate_fast                lvzip_inflate_fast
#define inflateInit                 lvzip_inflateInit
#define inflateInit2                lvzip_inflateInit2
#define inflateMark                 lvzip_inflateMark
#define inflatePrime                lvzip_inflatePrime
#define inflateReset                lvzip_inflateReset
#define inflateReset2               lvzip_inflateReset2
#define inflateSetDictionary        lvzip_inflateSetDictionary
#define inflateSync                 lvzip_inflateSync
#define inflateSyncPoint            lvzip_inflateSyncPoint
#define inflateUndermine            lvzip_inflateUndermine
#define uncompress                  lvzip_uncompress
#define z_errmsg                    z_z_errmsg
#define zcalloc                     lvzip_zcalloc
#define zcfree                      lvzip_zcfree
#define zError                      lvzip_zError
#define zlibCompileFlags            lvzip_zlibCompileFlags
#define zlibVersion                 lvzip_zlibVersion

#define unzClose                    lvzip_unzClose
#define unzClose2                   lvzip_unzClose2
#define unzCloseCurrentFile         lvzip_unzCloseCurrentFile
#define unzGetCurrentFileInfo       lvzip_unzGetCurrentFileInfo
#define unzGetCurrentFileInfo64     lvzip_unzGetCurrentFileInfo64
#define unzGetCurrentFileZStreamPos64   lvzip_unzGetCurrentFileZStreamPos64
#define unzGetFilePos               lvzip_unzGetFilePos
#define unzGetFilePos64             lvzip_unzGetFilePos64
#define unzGetGlobalComment         lvzip_unzGetGlobalComment
#define unzGetGlobalInfo            lvzip_unzGetGlobalInfo
#define unzGetGlobalInfo64          lvzip_unzGetGlobalInfo64
#define unzGetLocalExtrafield       lvzip_unzGetLocalExtrafield
#define unzGetOffset                lvzip_unzGetOffset
#define unzGetOffset64              lvzip_unzGetOffset64
#define unzGoToFilePos              lvzip_unzGoToFilePos
#define unzGoToFilePos64            lvzip_unzGoToFilePos64
#define unzGoToFirstFile            lvzip_unzGoToFirstFile
#define unzGoToFirstFile2           lvzip_unzGoToFirstFile2
#define unzGoToNextFile             lvzip_unzGoToNextFile
#define unzGoToNextFile2            lvzip_unzGoToNextFile2
#define unzLocateFile               lvzip_unzLocateFile
#define unzOpen                     lvzip_unzOpen
#define unzOpen64                   lvzip_unzOpen64
#define unzOpen2                    lvzip_unzOpen2
#define unzOpen2_64                 lvzip_unzOpen2_64
#define unzOpenCurrentFile          lvzip_unzOpenCurrentFile
#define unzOpenCurrentFile2         lvzip_unzOpenCurrentFile2
#define unzOpenCurrentFile3         lvzip_unzOpenCurrentFile3
#define unzOpenCurrentFilePassword  lvzip_unzOpenCurrentFilePassword
#define unzReadCurrentFile          lvzip_unzReadCurrentFile
#define unzRepair				    lvzip_unzRepair
#define unzSetOffset                lvzip_unzSetOffset
#define unzSetOffset64              lvzip_unzSetOffset64
#define unzStringFileNameCompare    lvzip_unzStringFileNameCompare
#define unztell				        lvzip_unztell
#define unztell64				    lvzip_unztell64
#define unzeof				        lvzip_unzeof
#define zipClose                    lvzip_zipClose
#define zipClose2                   lvzip_zipClose2
#define zipCloseFileInZip           lvzip_zipCloseFileInZip
#define zipCloseFileInZipRaw        lvzip_zipCloseFileInZipRaw
#define zipCloseFileInZipRaw64      lvzip_zipCloseFileInZipRaw64
#define zipOpen                     lvzip_zipOpen
#define zipOpen64                   lvzip_zipOpen64
#define zipOpen2                    lvzip_zipOpen2
#define zipOpen2_64                 lvzip_zipOpen2_64
#define zipOpen3                    lvzip_zipOpen3
#define zipOpenNewFileInZip         lvzip_zipOpenNewFileInZip
#define zipOpenNewFileInZip64       lvzip_zipOpenNewFileInZip64
#define zipOpenNewFileInZip2        lvzip_zipOpenNewFileInZip2
#define zipOpenNewFileInZip2_64     lvzip_zipOpenNewFileInZip2_64
#define zipOpenNewFileInZip3        lvzip_zipOpenNewFileInZip3
#define zipOpenNewFileInZip3_64     lvzip_zipOpenNewFileInZip3_64
#define zipOpenNewFileInZip4        lvzip_zipOpenNewFileInZip4
#define zipOpenNewFileInZip4_64     lvzip_zipOpenNewFileInZip4_64
#define zipRemoveExtraInfoBlock     lvzip_zipRemoveExtraInfoBlock
#define zipWriteInFileInZip         lvzip_zipWriteInFileInZip
#define gzopen						lvzip_gzopen
#define gzopen64					lvzip_gzopen64
#define gzdopen						lvzip_gzdopen
#define gzbuffer					lvzip_gzbuffer
#define gzseek						lvzip_gzseek
#define gzseek64					lvzip_gzseek64
#define gzsetparams					lvzip_gzsetparams
#define gzread						lvzip_gzread
#define gzwrite						lvzip_gzwrite
#define gzprintf					lvzip_gzprintf
#define gzputc						lvzip_gzputc
#define gzputs						lvzip_gzputs
#define gzgetc						lvzip_gzgetc
#define gzgets						lvzip_gzgets
#define gzungetc					lvzip_gzungetc
#define gzrewind					lvzip_gzrewind
#define gzeof						lvzip_gzeof
#define gzclearerr					lvzip_gzclearerr
#define gzflush						lvzip_gzflush
#define gzdirect					lvzip_gzdirect
#define gzerror						lvzip_gzerror
#define gzclose						lvzip_gzclose
#define gzclose_r					lvzip_gzclose_r
#define gzclose_w					lvzip_gzclose_w
#define gztell						lvzip_gztell
#define gztell64					lvzip_gztell64
#define gzoffset					lvzip_gzoffset
#define gzoffset64					lvzip_gzoffset64
#define gcrc32_combine				lvzip_crc32_combine
#define gcrc32_combine64			lvzip_crc32_combine64
